ARG POSTGRES_VERSION
ARG BASE_DIST

#============================================================================#
#========================| Postgres + Wal-g Image |==========================#
#============================================================================#
FROM postgres:$POSTGRES_VERSION-$BASE_DIST as postgres
ARG DEBIAN_FRONTEND=noninteractive
EXPOSE 5432
RUN apt update && apt install -y curl dialog sudo && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/lib/wal-g-utils/
COPY --chmod=755 --from=subfuzion/envtpl                  /bin/envtpl      /usr/bin/envtpl
COPY --chmod=755 --from=ghcr.io/shipilovds/wal-g-exporter /usr/bin/wal-g   /usr/bin/wal-g
COPY --chmod=755   docker/entrypoint.postgres.sh   /usr/local/bin/docker-entrypoint.sh
COPY --chmod=644   wal-g-utils/common.sh           /var/lib/wal-g-utils/
COPY --chmod=755   wal-g-utils/backup-fetch.sh     /var/lib/wal-g-utils/
COPY --chmod=755   wal-g-utils/backup-list.sh      /var/lib/wal-g-utils/
COPY --chmod=755   wal-g-utils/backup-push.sh      /var/lib/wal-g-utils/
COPY --chmod=755   wal-g-utils/wal-fetch.sh        /var/lib/wal-g-utils/
COPY --chmod=755   wal-g-utils/wal-push.sh         /var/lib/wal-g-utils/
COPY --chmod=755   wal-g-utils/recovery.sh         /var/lib/wal-g-utils/
COPY --chmod=644   configs/sudoers                 /etc/sudoers.d/wal-g
COPY --chmod=644   configs/postgresql.conf.tpl     /etc/postgres/
COPY --chmod=644   configs/pg_hba.conf             /etc/postgres/
COPY --chmod=644   docker/Dockerfile.postgres      /Dockerfile
